# syntax=docker/dockerfile:1

FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /

COPY /docker-gs-ping ./docker-gs-ping

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/docker-gs-ping"]

public/locales/en/public.jso